# Generated by Django 2.2.15 on 2020-08-25 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('issue', models.TextField()),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(default=None, null=True)),
                ('name_Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_ITRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
