# Generated by Django 2.2.15 on 2020-08-25 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '__first__'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumni_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('student_id', models.CharField(blank=True, max_length=8, null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('cv', models.FileField(default='../staticfiles/DefaultCV.txt', upload_to='documents')),
                ('is_active', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniJobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_apply', to='Alumni.Alumni')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_job', to='Home.Job')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='jobs_applied',
            field=models.ManyToManyField(through='Alumni.AlumniJobApplication', to='Home.Job'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='majors',
            field=models.ManyToManyField(related_name='alumni_majors', to='Home.Major'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.ManyToManyField(related_name='alumni_skills', to='Home.Skill'),
        ),
    ]
