# Generated by Django 2.2.13 on 2020-07-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200710_1241'),
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniJobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_apply', to='Alumni.Alumni')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_job', to='Home.Job')),
            ],
        ),
    ]
