# Generated by Django 2.2.13 on 2020-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200710_1241'),
        ('Alumni', '0002_alumnijobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='cv',
            field=models.FileField(default='../staticfiles/DefaultCV.txt', upload_to='documents'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='alumni',
            name='jobs_applied',
            field=models.ManyToManyField(through='Alumni.AlumniJobApplication', to='Home.Job'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.ManyToManyField(related_name='alumni_skills', to='Home.Skill'),
        ),
    ]
