# Generated by Django 2.2.13 on 2020-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_alumni_majors'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
