# Generated by Django 2.2.13 on 2020-07-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200712_1345'),
        ('Alumni', '0006_alumni_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniJobSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_status', models.CharField(choices=[('Saved', 'Saved'), ('Default', 'Default')], default='Default', max_length=15)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_job_id', to='Home.Job')),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_save', to='Alumni.Alumni')),
            ],
        ),
    ]
