# Generated by Django 2.2.13 on 2020-07-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0007_alumnijobsave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniJobSave',
        ),
    ]
