# Generated by Django 2.2.13 on 2020-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0008_delete_alumnijobsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
