# Generated by Django 2.2.15 on 2020-08-17 10:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0011_auto_20200813_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
