# Generated by Django 2.2.13 on 2020-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_auto_20200621_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
