# Generated by Django 2.2.13 on 2020-08-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0005_auto_20200811_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_active',
        ),
    ]
