# Generated by Django 2.2.13 on 2020-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0006_remove_employer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
