# Generated by Django 2.2.13 on 2020-08-12 05:44

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0007_employer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact_name',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='trade_license',
            field=models.FileField(default='../staticfiles/DefaultDP.jpg', upload_to='trade_licenses'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
