# Generated by Django 2.2.13 on 2020-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0008_auto_20200812_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
