# Generated by Django 2.2.13 on 2020-08-16 12:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0009_auto_20200813_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
