# Generated by Django 2.2.15 on 2020-08-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0010_auto_20200816_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='trade_license',
            field=models.FileField(default='../media/ICT108_Assignment.pdf', upload_to='trade_licenses'),
        ),
    ]
