# Generated by Django 2.2.15 on 2020-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0012_auto_20200818_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
