# Generated by Django 2.2.6 on 2020-05-21 09:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('to_show', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Deleted', 'Deleted')], default='Open', max_length=15)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_industry', to='Home.Industry')),
                ('job_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='Home.JobType')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_author', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='job_skills', to='Home.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='HelpDeskComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_admin', to='Admin.Admin')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
