# Generated by Django 2.2.13 on 2020-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Umm al-Qaiwain', 'Umm al-Qaiwain'), ('Fujairah', 'Fujairah'), ('Ajman', 'Ajman'), ('Ra’s al-Khaimah', 'Ra’s al-Khaimah')], max_length=100),
        ),
    ]
