# Generated by Django 2.2.15 on 2020-08-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200825_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
    ]
