# Generated by Django 2.2.13 on 2020-07-12 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_max',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
