# Generated by Django 2.2.15 on 2020-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200827_1521'),
        ('Home', '0003_auto_20200829_1301'),
    ]

    operations = [
    ]
