# Generated by Django 2.2.15 on 2020-08-30 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_merge_20200830_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
