# Generated by Django 2.2.13 on 2020-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200712_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration_type',
            field=models.CharField(choices=[('In Days', 'Days'), ('In Weeks', 'Weeks'), ('In Months', 'Months')], default='In Months', max_length=10),
            preserve_default=False,
        ),
    ]
