# Generated by Django 2.2.15 on 2020-08-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200830_1624'),
        ('Home', '0005_auto_20200830_1550'),
    ]

    operations = [
    ]
