# Generated by Django 2.2.13 on 2020-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_job_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'In Days'), ('Weeks', 'In Weeks'), ('Months', 'In Months')], max_length=10),
        ),
    ]
