# Generated by Django 2.2.13 on 2020-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200712_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='type_name',
            field=models.SlugField(unique=True),
        ),
    ]
