# Generated by Django 2.2.13 on 2020-07-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200719_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=20),
        ),
    ]
