# Generated by Django 2.2.13 on 2020-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200720_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='type_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
