# Generated by Django 2.2.13 on 2020-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20200724_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
