# Generated by Django 2.2.13 on 2020-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20200813_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration_type',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Permanent', 'Permanent')], max_length=10),
        ),
    ]
