# Generated by Django 2.2.15 on 2020-08-25 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('student_id', models.CharField(max_length=8, unique=True)),
                ('personal_email', models.EmailField(max_length=100)),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('cv', models.FileField(default='../staticfiles/DefaultCV.txt', upload_to='documents')),
                ('is_active', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentJobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_apply', to='Student.Student')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_job', to='Home.Job')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='jobs_applied',
            field=models.ManyToManyField(through='Student.StudentJobApplication', to='Home.Job'),
        ),
        migrations.AddField(
            model_name='student',
            name='majors',
            field=models.ManyToManyField(related_name='student_majors', to='Home.Major'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(related_name='student_skills', to='Home.Skill'),
        ),
    ]
