# Generated by Django 2.2.13 on 2020-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(max_length=100),
        ),
    ]
