# Generated by Django 2.2.13 on 2020-07-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200710_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alumni_status',
        ),
    ]
