# Generated by Django 2.2.13 on 2020-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_major'),
        ('Student', '0003_remove_student_alumni_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='majors',
            field=models.ManyToManyField(related_name='student_majors', to='Home.Major'),
        ),
    ]
