# Generated by Django 2.2.13 on 2020-08-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10, null=True),
        ),
    ]
